### ISSUE TITLE
How about a little Ui/Ux retouch ?

### ISSUE THREAD

**Issue by daguitosama** [whoiskatrin/sql-translator#12]
I founded super interesting the tool, but while trying to use I experience some little issues like to much tiny text areas to fit content, and I could not help my self to wire up a little Ui iteration to help with that 😂
If you find it useful let me know, will be happy to help. 

## Resources:
- Copy  & Headings  Font -> [Clash Grotesk
](https://www.fontshare.com/fonts/clash-grotesk)
- Code Font -> [Fira Code](https://fonts.google.com/specimen/Fira+Code?query=fira+code)
- [Figma File](https://www.figma.com/file/jWMUmILfTg5tNk7MrUNX1K/Untitled?node-id=0%3A1&t=Nb5XGzZ4nx8aUjRP-1)

## Previews
![sql-translator-concept](https://user-images.githubusercontent.com/34744883/224896506-c4da268d-3ed3-48ab-9292-f9228e950e81.png)

**Comment by whoiskatrin** [comment]
Hi, thank you for the suggestion, we are currently working on a new design that should be ready soon.
