### ISSUE TITLE
Leaking the API key?

### ISSUE THREAD

**Issue by alan2207** [whoiskatrin/sql-translator#2]
Hey @whoiskatrin, nice project, congrats!

I was curious about its implementation and noticed that the openai API key is publicly visible. That's because the props from `getServerSideProps` are injected into the page. This might lead to unexpected billing costs If someone decides to abuse it.

<img width="1074" alt="Screenshot 2023-03-12 at 08 14 28" src="https://user-images.githubusercontent.com/12713315/224530094-13c75233-1ce5-444e-aaca-f10375f28931.png">

Have you considered using an API route for the translation part where you could use the API key without exposing it to the public??

**Comment by whoiskatrin** [comment]
yes, finally fixed it, not an issue any more
