### ISSUE TITLE
Some of the text is not readable

### ISSUE THREAD

**Issue by Madmorgan007** [whoiskatrin/sql-translator#20]
Hello,

While looking at this project I found some of the text is not read, white text on white background. please see images.

![image](https://user-images.githubusercontent.com/19917093/225241907-7199165a-f73f-407f-b94d-0d38f196d602.png)
![image](https://user-images.githubusercontent.com/19917093/225241985-0fd99891-ef51-4407-9e5c-653d387fd791.png)

**Comment by whoiskatrin** [comment]
this should be fixed, could you try to reproduce it again, please @Madmorgan007

**Comment by shuabrannigan** [comment]
had same issue, toggling the darkmode fixed it

<img width="550" alt="Screenshot 2023-03-16 at 8 35 14 pm" src="https://user-images.githubusercontent.com/59857118/225583716-724d0a0a-5715-4555-9325-821c9cc53645.png">

<img width="525" alt="Screenshot 2023-03-16 at 8 41 00 pm" src="https://user-images.githubusercontent.com/59857118/225585145-c4742ff4-adcf-43ff-af66-72f757ee4309.png">

**Comment by whoiskatrin** [comment]
@shuabrannigan could you please provide details to reproduce?
OS, versions and etc

**Comment by shuabrannigan** [comment]
hey i am running macOS, have sussed whats causing it; 

it happens when the theme in local storage is set to 'system' toggling the darkmode sets the theme as either 'light' or 'dark'.

**Comment by shuabrannigan** [comment]
you can reproduce by clearing the local storage value

**Comment by shuabrannigan** [comment]
@whoiskatrin happy to fix if you want to assign?
