### ISSUE TITLE
Dark/light toggle is broken

### ISSUE THREAD

**Issue by eduardconstantin** [whoiskatrin/sql-translator#37]
This is how it looks when you enter the first time on the website:

![image](https://user-images.githubusercontent.com/9199763/226282817-59b24920-f129-4b51-8ac8-821f52cac977.jpeg)

You can replicate this issue by using incognito.
Also, the border on the right card is different from the one on the left.

**Comment by whoiskatrin** [comment]
Fixed! Close if happy @eduardconstantin
