### ISSUE TITLE
npm run build failed

### ISSUE THREAD

**Issue by parkerqian** [whoiskatrin/sql-translator#44]
npm install

npm run build ,and got the failure 
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/4987818/226671869-b0679f91-d6ed-432d-82b5-223d28cd4734.png">

**Comment by parkerqian** [comment]
nmp -v :6.14.4

**Comment by whoiskatrin** [comment]
@parkerqian just tried and had a successful build, could you try again? make sure you have every dependency installed correctly

**Comment by parkerqian** [comment]
> @parkerqian just tried and had a successful build, could you try again? make sure you have every dependency installed correctly

This may be caused by the version of Node.js. I will try again later. Thank you.
